[package]
name = "Kuplung-Rust"
description = "Rust port of Kuplung"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/supudo/Kuplung-Rust"
authors = ["Sergey Petrov <supudo@gmail.com>"]
keywords = ["OpenGL", "graphics", "rendering"]
build = "build.rs"

[dependencies]
gl = "0.14.0"
sdl2 = "0.37.0"
bytemuck = "1.16.3"
imagine = "0.5.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"